config/routes.rb
Rails.application.routes.draw do

	get '/movies/admin', to: 'movies#admin'
	resources :movies 
	resources :auditoria
	resources :showtimes do
		resources :sales, only: [:new, :create]
	end

	resources :sales, only: [:index, :destroy, :show]



	root 'movies#index'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	def index
		@movies = Movie.all
		@as_admin = false
	end

	def admin
		@movies = Movie.all
		@auditoria = Auditorium.all
		@as_admin = true
		render 'index'
	end

	def show
		@movie = Movie.find_by(id: params[:id])
		if @movie
			render "show"
		else
			redirect_to :movies
		end 
	end

	def new
		@movie = Movie.new
		render "new"
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			render "show"
		else
			@errors = @movie.errors.full_messages
			render "new"
		end
	end

	def edit
		@movie = Movie.find_by(id: params[:id])
		if @movie
			render "edit"
		else
			redirect_to :movies
		end
	end

	def update
		@movie = Movie.find_by(id: params[:id])
		if @movie
			if @movie.update_attributes(movie_params)
				render "show"
			else
				@errors = @movie.errors.full_messages
				render "edit"
			end
		else
			redirect_to :showtimes
		end
	end

	def destroy
		@movie = Movie.find_by(id: params[:id])
		if @movie
			@movie.destroy
			redirect_to :movies
		else
			redirect_to :root
		end
	end

	private

	def movie_params
    params.require(:movie).permit(:title, :director, :synopsis, :run_time, :cost)
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
	<%= label(:movie, :title, "Title:") %><%= f.text_field :title -%>
	<%= label(:movie, :director, "Director:") %><%= f.text_field :director -%>
	<%= label(:movie, :synopsis, "Synopsis:") %><%= f.text_field :synopsis -%>
	<%= label(:movie, :run_time, "Run Time (minutes):") %><%= f.text_field :run_time -%>
	<%= label(:movie, :cost, "Cost:") %><%= f.text_field :cost -%>
	<%= f.submit id: "submit_btn" -%>
<% end %>

app/views/movies/edit.html.erb
<h2>Edit Movie</h2>

<%= render "/errors" %>

<%= render "form" %>

app/views/movies/index.html.erb
<% if @as_admin %>
	<div id="admin_tasks">
			<div><%= link_to "Movie Tasks", new_movie_path %></div>
	  	<div><%= link_to "Showtime Tasks", new_showtime_path %></div>
	  	<div><%= link_to "Auditorium Tasks", auditoria_path %></div>
	</div>
<% end %>

<h1>Currently Playing:</h1>

<div>
	<% @movies.each do |movie| %>

		<% if movie.showtimes.any? %>
			<ul>
				<h2><a href="movies/<%= movie.id %>"><%= movie.title %></a></h2>
	
				<% if @as_admin %>
					<div><%= link_to "Edit", edit_movie_path(movie) %> <%= link_to "Delete", movie_path(movie), :method => :delete %></div>
				<% end %>
	
				<p>Run Time: <%= movie.run_time %></p>
				<% movie.unique_showdates.each do |showdate| %>
					<li>
						<h3><%= pretty_date(showdate.date) %>
							<% if @as_admin %>
								<%= link_to "Edit", edit_showtime_path(showdate) %> <%= link_to "Delete", showtime_path(showdate), :method => :delete %>
							<% end %>
						</h3>
					</li>
				<% end %>
			
			</ul>
		<% end %>
	<% end %>
</div>

app/views/movies/new.html.erb
<h2>Enter a New Movie</h2>

<%= render "/errors" %>

<%= render "form" %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<h3>Directed by <%= @movie.director %></h3>
<h3>Run time: <%= @movie.run_time %></h3>
<h3> <em>Synopsis:</em> <%= @movie.synopsis %></h3>

<%= render "/errors" %>

<h2>Showtimes:</h2>
<ul>
	<% @movie.unique_showdates.each do |showdate| %>
		<li class="baloo">
			<h3><%= pretty_date(showdate.date) %></h3>
			<ul>
				<% @movie.showtimes_on_date(showdate.date).each do |showtime| %>
					<li><%= pretty_time(showtime.time) %> <%= (showtime.is_available?) ? (link_to "Buy Tickets >>", new_showtime_sale_path(showtime)) : ("Sold Out") %></li>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>