config/routes.rb
Rails.application.routes.draw do

	get '/movies/admin', to: 'movies#admin'
	resources :movies 
	resources :auditoria
	resources :showtimes do
		resources :sales, only: [:new, :create]
	end

	resources :sales, only: [:index, :destroy, :show]



	root 'movies#index'

end

app/models/sale.rb
class Sale < ApplicationRecord
	# t.string :confirmation_no
	# t.integer :customer_id
	# t.integer :showtime_id
    	
	belongs_to :customer
	belongs_to :showtime
	has_one :auditorium, through: :showtime
	has_one :movie, through: :showtime

	validates :confirmation_no, presence: true, numericality: { only_integer: true, greater_than: 0 }
	validates :customer_id, presence: true, numericality: { only_integer: true, greater_than: 0 }
	validates :showtime_id, presence: true, numericality: { only_integer: true, greater_than: 0 }

	validate :available_seats

	private
  def available_seats
		if showtime.sales.count >= auditorium.capacity
			errors.add(:confirmation_no, "cannot be issued.  No seating available for this showtime.")	
		end
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	def index
		@sales = Sale.all
	end

	def new
		@showtime = Showtime.find_by(id: params[:showtime_id])
		if @showtime && @showtime.is_available?
			render "new"
		else
			redirect_to :root
		end 
	end

	def create
		@showtime = Showtime.find_by(id: params[:showtime_id])
		if @showtime
			if @showtime.is_available?
				@customer = Customer.new(customer_params)
				if @customer.save
					@sale = Sale.new(confirmation_no: generate_confirmation_no)
					@sale.showtime = @showtime
					@sale.customer = @customer
					if @sale.save
						TicketMailer.ticket_email(@customer, @sale).deliver_now
						redirect_to @sale
					else
						# since sale can't be made
						@customer.destroy
						@errors = @sale.errors.full_messages
						render "new"
					end
				else
					# since customer validations failed
					@errors = @customer.errors.full_messages
					render "new"
				end
			else
				# since no available capacity in the auditorium
				@errors = ["Sorry, but this showtime is sold out."]
				@movie = @showtime.movie
				render "movies/show"
			end
		else
			# since the showtime is unavailable 
			redirect_to :root
		end
	end

	def show
		@sale = Sale.find_by(id: params[:id])
		if @sale
			@showtime = @sale.showtime
			render "show"
		else
			@errors = @sale.errors.full_messages
			render "index"
		end 
	end

	def destroy
		@sale = Sale.find_by(id: params[:id])
		if @sale
			@sale.destroy
			redirect_to :sales
		else
			redirect_to :root
		end
	end

	private
	def customer_params
    params.require(:customer).permit(:name, :email, :email_confirmation, :cc_number, :cc_expiration_month, :cc_expiration_year)
  end

  def generate_confirmation_no
		confirmation_no = ""
		loop do
			confirmation_no = rand(100000..999999).to_s
			break unless Sale.where(confirmation_no: confirmation_no).any?
		end
		confirmation_no
  end

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/index.html.erb
<h1>Sales:</h1>

<table>
  <tr>
    <th>Confirmation No.</th>
    <th>Movie</th>
    <th>Price</th>
    <th>Auditorium</th>
    <th>Date</th>
    <th>Customer ID</th>
    <th>Delete</th>
  </tr>

  <% @sales.joins(:showtime).order("showtimes.date desc, showtimes.time").each do |sale| %>
  <tr>
    <td><%= link_to sale.confirmation_no, sale %></td>
    <td><%= link_to sale.movie.title, sale.movie %></td>
    <td>$<%= sale.movie.cost %></td>
    <td><%= sale.auditorium.name %></td>
    <td><%= pretty_date(sale.showtime.date) %>, <%= pretty_time(sale.showtime.time) %></td>
    <td><%= sale.customer.id %></td>
    <td><%= link_to "Delete", sale_path(sale), :method => :delete %></td>
  </tr>
	<% end %>
</table>
</div>

app/views/sales/new.html.erb
<h2>Ticket Purchase </h2>
<%= render "/errors" %>

<div>You are purchasing a ticket for the <%= pretty_date(@showtime.date) %>, <%= pretty_time(@showtime.time) %> showing of <%= @showtime.movie.title %>.</div>
<div>The charge will be $<%= @showtime.movie.cost %>.  Please provide your information below:</div>

<%= form_for :customer, url: :showtime_sales do |f| %>
	<%= label(:movie, :name, "Name:") %><%= f.text_field :name %>
	<%= label(:movie, :email, "Email:") %><%= f.text_field :email %>
	<%= label(:movie, :email_confirmation, "Confirm Email:") %><%= f.text_field :email_confirmation %>
	<%= label(:movie, :cc_number, "Credit Card (16 digits):") %><%= f.text_field :cc_number %>
	<%= label(:movie, :cc_expiration_month, "Expiration Date (MM / YYYY):", id: "customer_cc_expiration_month_label") %><%= f.text_field :cc_expiration_month %> / <%= f.text_field :cc_expiration_year %>
	<%= f.submit 'Purchase', id: "submit_btn" %>
<% end %>

app/views/sales/show.html.erb
<h1 class="baloo">Thank you for your $<%= @sale.movie.cost %> purchase, <%= @sale.customer.name %>!</h1>

<h3 class="">A ticket has been emailed to <%= @sale.customer.email %></h3>

<%= render 'showtimes/showtime' %>