config/routes.rb
Rails.application.routes.draw do

	get '/movies/admin', to: 'movies#admin'
	resources :movies 
	resources :auditoria
	resources :showtimes do
		resources :sales, only: [:new, :create]
	end

	resources :sales, only: [:index, :destroy, :show]



	root 'movies#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Popcorn Cinema - Where Everything Is A Little Corny</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Baloo|Pacifico" rel="stylesheet">

  </head>

  <body>
    <%= link_to root_path, id: "logo-link" do %>
    <div id="logo">
      <h1 id="title" class="baloo">Popcorn Cinema</h1>
      <h2 id="tagline" class="pacifico">Where Everything Is A Little Corny</h2>  
    </div>
    <% end -%>
    <div id="container">

      <div id="frame">

        <div id="popcorn" class="frame-element"></div>
        <div id="box-top-left" class="frame-element"></div>
        <div id="box-top-right" class="frame-element"></div>
        <div id="box-mid-left" class="frame-element"></div>
        <div id="box-mid-right" class="frame-element"></div>
        <div id="box-bottom-left" class="frame-element"></div>
        <div id="box-bottom-right" class="frame-element"></div>

        <div id="content">
          <nav><%= link_to "Home", movies_path %> | <%= link_to "Admin", movies_admin_path %></nav>
          <%= yield %>
        </div>

      </div>
    </div>
  </body>
</html>